# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'news_HolmogorovDmitry_l3' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
	pod 'YYWebImage'
  # Pods for news_HolmogorovDmitry_l3

end
